source "https://rubygems.org"

ruby "3.3.9"

gem "sinatra", "~> 4.2"
gem "sqlite3", "~> 2.9"
gem "rake", "~> 13.2"
gem "rackup", "~> 2.2"
gem "webrick", "~> 1.9"

group :test do
  gem "minitest", "~> 5.25"
  gem "rack-test", "~> 2.2"
  gem "rexml", "~> 3.3"
end
