require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "lib" << "test"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end

task default: :test

desc "Rebuild window_observations from raw_snapshots using the current normalizer"
task :reprocess do
  $LOAD_PATH.unshift(File.expand_path("lib", __dir__))
  require "agent_usage/reprocessor"
  result = AgentUsage::Reprocessor.run
  puts "Reprocessed #{result[:snapshots]} snapshot(s) into #{result[:observations]} window observation(s)."
end
